# Generated by Django 3.1.1 on 2020-09-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='code',
            field=models.CharField(choices=[('a1', 'A1'), ('a2', 'A2'), ('a3', 'A3')], max_length=2, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Name'),
        ),
    ]
