# Generated by Django 3.1.1 on 2020-09-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0002_auto_20200902_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='code',
            field=models.CharField(max_length=2, unique=True, verbose_name='Code'),
        ),
    ]
