version: '3'

services:

#  postgres:
#    image: postgres
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_DB=dev
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
#      - migration
#
#  migration:
#    build: .
#    command: python manage.py migrate
#    volumes:
#      - .:/code
#    depends_on:
#      - postgres