version: '3'

services:

  postgres:
    image: mdillon/postgis:10
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

#  web:
#    build: .
#    command: python manage.py runserver 127.0.0.1:8000
#    volumes:
#      - .:/code
#    ports:
#      - "8000:8000"
#    depends_on:
#      - postgres
#      - migration
#
#  migration:
#    build: .
#    command: python manage.py migrate
#    volumes:
#      - .:/code
#    depends_on:
#      - postgres