# Generated by Django 3.1.1 on 2020-09-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20200902_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='static/images', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='category',
            name='translation',
            field=models.CharField(blank=True, max_length=50, verbose_name='Translation'),
        ),
    ]
