# Generated by Django 3.1.1 on 2020-09-03 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('plural', models.CharField(blank=True, max_length=20, verbose_name='Plural')),
                ('translation', models.CharField(max_length=20, verbose_name='Translation')),
                ('transcription', models.CharField(blank=True, max_length=30, verbose_name='Transcription')),
                ('example', models.CharField(blank=True, max_length=255, verbose_name='Phrase example')),
                ('sound', models.FileField(blank=True, null=True, upload_to='static/sounds', verbose_name='Sound')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='static/images', verbose_name='Picture')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='themes.theme')),
            ],
            options={
                'verbose_name': 'Word',
                'verbose_name_plural': 'Words',
                'db_table': 'words',
                'ordering': ('name',),
            },
        ),
    ]
