# Generated by Django 3.1.1 on 2020-09-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='plural',
            field=models.CharField(blank=True, max_length=30, verbose_name='Plural'),
        ),
        migrations.AlterField(
            model_name='word',
            name='example',
            field=models.CharField(blank=True, max_length=255, verbose_name='Phrase example'),
        ),
        migrations.AlterField(
            model_name='word',
            name='picture',
            field=models.URLField(blank=True, verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='word',
            name='sound',
            field=models.URLField(blank=True, verbose_name='Sound'),
        ),
        migrations.AlterField(
            model_name='word',
            name='transcription',
            field=models.CharField(blank=True, max_length=30, verbose_name='Transcription'),
        ),
    ]
