# Generated by Django 3.1.1 on 2020-09-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_auto_20200902_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/images', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='word',
            name='plural',
            field=models.CharField(blank=True, max_length=20, verbose_name='Plural'),
        ),
        migrations.AlterField(
            model_name='word',
            name='sound',
            field=models.FileField(blank=True, null=True, upload_to='static/sounds', verbose_name='Sound'),
        ),
    ]
