# Generated by Django 3.1.1 on 2020-09-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='translation',
            field=models.CharField(default='', max_length=50, verbose_name='Translation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='theme',
            name='photo',
            field=models.URLField(blank=True, verbose_name='Photo'),
        ),
    ]
